### ISSUE TITLE
Add namespace to app of apps application

### ISSUE THREAD

**Issue by tosmi** [tjungbauer/openshift-clusterconfig-gitops#4]
we would like to reuse the bootstrap app of apps for

- to manage cluster app of apps with argo
- reuse app of apps for application gitops

this requires creating the app of apps via argocd, and in different namespaces. currently the namespaces is set in the call to `helm template --namespace ...`.

if the namespace field is included in the template we could simply reuse it.

https://github.com/tjungbauer/openshift-clusterconfig-gitops/blob/a9c5435d88a186daa9f7dd2e91c2600b529b5032/base/init_app_of_apps/templates/argocd_resources_manager.yaml#L5

**Comment by tjungbauer** [comment]
Should be fixed with the commit: https://github.com/tjungbauer/openshift-clusterconfig-gitops/commit/df6567377a120cc8d33c11a0c64c5bd74cd340e1 

Besides the namespace, the object name must be a variable too then. 

The commit introduces three new variables:

```yaml
# -- Name of the App of Apps
# @default -- argocd-resources-manager
name: argocd-resources-manager

# -- Namespace for the App of Apps
# @default -- openshift-gitops
namespace: openshift-gitops

# -- Namespace on the destination cluster
# @default -- openshift-gitops
destinationNamespace: openshift-gitops
```
